# Deploy last stable version of repoXplorer published on docker hub.

version: '3'
services:
  repoxplorer:
    image: repoxplorer-holo:latest
    container_name: repoxplorer-holo
    ports:
      - 51000:51000
    volumes:
      - repoxplorer-data:/usr/local/share/repoxplorer
      - elasticsearch-data:/var/lib/elasticsearch
      - $PWD/docker-data/conf:/etc/repoxplorer/defs:z
volumes:
  elasticsearch-data:
  repoxplorer-data:

